[pytest]
# 测试用例目录（指定tests目录）
testpaths = tests
# 用例命名规则（匹配test_*.py文件中的test_*函数）
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# 禁用不必要的警告
addopts = -p no:warnings
# 编码格式
console_output_encoding = utf-8